import csv

data = {
    "IT Developer": [
        ("writing", "Technical Writer"),
        ("drawing", "UI/UX Designer"),
        ("public speaking", "IT Consultant"),
        ("logic", "Backend Developer"),
        ("analysis", "Data Analyst"),
        ("communication", "Project Manager IT"),
        ("coding", "Fullstack Developer"),
        ("troubleshooting", "IT Support Specialist"),
        ("cybersecurity", "Cybersecurity Analyst"),
        ("mathematics ", "Software Engineer"),
        ("algorithm", "Machine Learning Engineer"),
        ("scripting", "DevOps Engineer"),
        ("cloud computing", "Cloud Architect"),
        ("computer science ", "Research Scientist AI"),
        ("blockchain", "Blockchain Developer"),
        ("automation", "Test Automation Engineer"),
        ("robotics", "Robotics Engineer"),
        ("mobile program", "Mobile Developer"),
        ("frontend", "Frontend Engineer"),
        ("database", "Database Administrator"),
    ],
    "Design": [
        ("drawing", "Illustrator"),
        ("color & composition", "Graphic Designer"),
        ("photography", "Digital Imaging Specialist"),
        ("ui/ux", "Web Designer"),
        ("motion", "Motion Graphic Artist"),
        ("creativity", "Art Director"),
        ("branding", "Creative Strategist"),
        ("storytelling", "Visual Content Creator"),
        ("observation", "Layout Designer"),
        ("design software", "Multimedia Designer"),
        ("typography", "Typographer"),
        ("character design", "Character Designer"),
        ("comics", "Comic Artist"),
    ],
    "Health": [
        ("caring", "Nurse"),
        ("biology", "General Practitioner"),
        ("high concentration", "Surgeon"),
        ("attention to detail", "Pharmacist"),
        ("empathy", "Clinical Psychologist"),
        ("public speaking", "Health Educator"),
        ("physical strength", "Paramedic"),
        ("memorization", "Specialist Doctor"),
        ("analysis", "Medical Researcher"),
        ("communication", "Nutrition Counselor"),
        ("organization", "Hospital Manager"),
        ("environmental awareness", "Community Nutritionist"),
        ("education", "Health Educator"),
    ],
    "Education & Training": [
        ("public speaking", "Teacher"),
        ("patience", "Lecturer"),
        ("literacy", "Literacy Facilitator"),
        ("writing", "Educational Book Writer"),
        ("edtech", "Educational Technology Specialist"),
        ("observation", "Educational Psychologist"),
        ("online teaching", "E-Learning Coach"),
        ("student observation", "School Psychologist"),
        ("creativity", "Educational Media Developer"),
        ("analysis", "Education Researcher"),
        ("digital literacy", "E-learning Instructor"),
        ("communication", "School Counselor"),
        ("counseling", "Career Counselor"),
        ("interpersonal", "Career Coach"),
        ("technology", "Children’s Coding Instructor"),
        ("organization", "School Principal"),
    ],
    "Business & Management": [
        ("negotiation", "Sales Manager"),
        ("analysis", "Business Analyst"),
        ("financial analysis", "Financial Analyst"),
        ("tax accounting", "Tax Consultant"),
        ("financial planning", "Financial Planner"),
        ("calculation", "Actuary"),
        ("investment", "Investment Analyst"),
        ("asset management", "Asset Manager"),
        ("statistics", "Credit Analyst"),
        ("reporting", "Accounting Staff"),
        ("communication", "Public Relations Specialist"),
        ("leadership", "Project Manager"),
        ("strategy", "Business Consultant"),
        ("digital marketing", "Digital Marketer"),
        ("accounting", "Auditor"),
        ("problem solving", "Entrepreneur"),
        ("time management", "Event Organizer"),
        ("decision making", "Operations Manager"),
        ("risk management", "Risk Analyst"),
        ("capital market", "Financial Analyst"),
        ("HR management", "HR Specialist"),
    ],
    "Music": [
        ("playing guitar", "Guitarist"),
        ("singing", "Vocalist"),
        ("music composition", "Composer"),
        ("music theory", "Music Teacher"),
        ("music production", "Music Producer"),
        ("mixing", "Sound Engineer"),
        ("stage", "Music Director"),
        ("multi-talented", "Indie Musician"),
    ],
    "Sports": [
        ("physical agility", "Sports Coach"),
        ("team strategy", "Sports Team Manager"),
        ("motivation", "Fitness Consultant"),
        ("teaching", "Gym Instructor"),
        ("observation", "Referee"),
        ("competitive spirit", "Professional Athlete"),
        ("physiology", "Sports Physiotherapist"),
        ("outdoor", "Outdoor Sports Guide"),
    ],
    "Language & Communication": [
        ("creative writing", "Copywriter"),
        ("editorial", "Editor"),
        ("multilingual", "Translator"),
        ("broadcasting", "Broadcaster"),
        ("interviewing", "Reporter"),
        ("digital content", "Content Creator"),
        ("visual communication", "Brand Strategist"),
        ("scriptwriting", "Scriptwriter"),
        ("storytelling", "Podcaster"),
        ("rhetoric", "Host/Moderator"),
    ],
    "Art": [
        ("painting", "Painter"),
        ("sculpting", "Sculptor"),
        ("creativity", "Contemporary Artist"),
        ("art gallery", "Art Curator"),
        ("photography", "Art Photographer"),
        ("self-expression", "Performance Artist"),
        ("visual storytelling", "Storyboard Artist"),
        ("installation art", "Installation Artist"),
        ("self-expression", "Actor"),
        ("body coordination", "Dancer"),
        ("vocals", "Singer"),
        ("stage", "Theatre Production Manager"),
        ("scriptwriting", "Dramaturg"),
        ("art direction", "Director"),
        ("lighting", "Lighting Designer"),
        ("live music", "Performer"),
        ("costumes", "Costume Designer"),
        ("sound setup", "Sound Engineer"),
    ],
    "Environment": [
        ("analysis", "Environmental Scientist"),
        ("research", "Environmental Researcher"),
        ("communication", "Environmental Activist"),
        ("planning", "Environmental Consultant"),
        ("field work", "Conservation Officer"),
        ("advocacy", "Environmental Lawyer"),
        ("education", "Environmental Educator"),
        ("engineering", "Environmental Engineer"),
    ],
    "Journalism & Media": [
        ("writing", "Journalist"),
        ("observation", "Reporter"),
        ("communication", "News Presenter"),
        ("research", "Fact Checker"),
        ("editing", "Editor"),
        ("social media", "Content Creator"),
        ("interviewing", "Interviewer"),
        ("photography", "Photojournalist"),
        ("multimedia", "Video Journalist"),
    ],
    "Engineering & Industry": [
        ("mechanics", "Mechanical Engineer"),
        ("electronics", "Electronics Engineer"),
        ("architecture", "Architect"),
        ("energy", "Energy Engineer"),
        ("planning", "Construction Project Manager"),
        ("production", "Factory Manager"),
        ("system analysis", "Systems Engineer"),
        ("3D modeling", "CAD Designer"),
        ("quality control", "Quality Assurance Engineer"),
        ("material testing", "Material Scientist"),
    ],
    "Tourism & Hospitality": [
        ("hospitality", "Hotel Manager"),
        ("multilingual", "Tour Guide"),
        ("customer service", "Receptionist"),
        ("attention to detail", "Event Planner"),
        ("logistics", "Hotel Operations Manager"),
        ("culinary", "Chef"),
        ("branding", "Tourism Brand Manager"),
        ("destination photography", "Travel Photographer"),
        ("negotiation", "Travel Agent"),
        ("multicultural awareness", "International Resort Manager"),
    ],
    "Agriculture & Livestock": [
        ("plants", "Agronomist"),
        ("livestock", "Livestock Farmer"),
        ("research", "Agricultural Researcher"),
        ("product processing", "Agribusiness Manager"),
        ("extension services", "Agricultural Extension Officer"),
        ("animal health", "Veterinarian"),
        ("food technology", "Food Technology Specialist"),
        ("land management", "Agricultural Consultant"),
        ("dairy production", "Dairy Farm Manager"),
        ("animal feed", "Animal Nutritionist"),
    ],
    "Transportation & Logistics": [
        ("shipping", "Logistics Manager"),
        ("routing", "Transportation Planner"),
        ("supply chain", "Supply Chain Analyst"),
        ("warehouse management", "Warehouse Supervisor"),
        ("distribution", "Distribution Coordinator"),
        ("procurement", "Procurement Specialist"),
        ("maritime transport", "Ship Navigator"),
        ("air transport", "Flight Operations Manager"),
        ("information technology", "Transport Systems Analyst"),
    ],
    "Social & Humanities": [
        ("communication", "Public Relations Specialist"),
        ("research", "Social Researcher"),
        ("counseling", "Social Worker"),
        ("data analysis", "Public Policy Analyst"),
        ("language", "Translator"),
        ("culture", "Anthropologist"),
        ("psychology", "Psychologist"),
        ("education", "Teacher"),
        ("journalism", "Journalist"),
        ("international relations", "Diplomat"),
    ],
    "Transportation & Logistics": [
        ("shipping", "Logistics Manager"),
        ("routing", "Transportation Planner"),
        ("supply chain", "Supply Chain Analyst"),
        ("warehouse management", "Warehouse Supervisor"),
        ("distribution", "Distribution Coordinator"),
        ("procurement", "Procurement Specialist"),
        ("maritime transport", "Ship Navigator"),
        ("air transport", "Flight Operations Manager"),
        ("information technology", "Transport Systems Analyst"),
        ("planning", "Transportation Consultant"),
    ],
    "Law & Government": [
        ("debating", "Lawyer"),
        ("analysis", "Judge"),
        ("constitution", "Legislator"),
        ("issue analysis", "Public Policy Analyst"),
        ("legal precision", "Notary"),
        ("communication", "Prosecutor"),
        ("administration", "Government Officer"),
        ("advocacy", "Human Rights Activist"),
        ("regulation", "Legal Officer"),
        ("social relations", "Diplomat"),
    ]
}

with open('career_dataset.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(["Field", "Skill", "Career"])  # Header

    for field, pairs in data.items():
        for skill, career in pairs:
            writer.writerow([field, skill.strip(), career])
